version: '3.7'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      DATABASE_URL: mydb:mydbpassword@db/mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
