name: AWS CDK Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      NODE_VERSION: '20'
      PYTHON_VERSION: '3.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print directory contents
        run: ls -la

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/*.json') }}

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/*.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update AWS CDK
        run: sudo npm install -g aws-cdk@latest

      - name: Compile and move NestJS Backend API to lambda's relative folder
        run: |
          cd backend/api
          npm ci
          npm run build-lambda
          mv dist ../lambdas/nestjs_serverless
      
      - name: Inject prisma client into Typescript Lambdas that use DB
        run: |
          db_lambdas_dirs=(
            synchronizer
          )

          for dir in "${db_lambdas_dirs[@]}"; do
            mkdir -p "./backend/lambdas/typescript/$dir/prisma"
            cp -r ./backend/api/prisma/. "./backend/lambdas/typescript/$dir/prisma/"
          done

        shell: bash
        timeout-minutes: 10
        continue-on-error: false


      - name: Transpile TypeScript Lambdas to JS (as Lambdas do not support TS directly)
        run: |
          cd backend/lambdas/typescript
          for directory in */; do
            echo "Transpiling $directory to JS"
            cd "$directory"
            npm install --save typescript
            npm run build-lambda
          done

      - name: Install CDK dependencies and Python requirements
        run: |
          npm install -g aws-cdk
          python3 -m pip install -r requirements.txt

      - name: Bootstrap and synthesize CDK app
        run: |
          mkdir -p cdk.out
          cdk bootstrap
          cdk synth --app="python3 app.py" --output=cdk.out

      - name: Deploy to AWS
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cdk deploy --app="cdk.out" --require-approval=never --all --outputs-file=./cdk_outputs.json

      - name: Deploy DB
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd backend/api
          npm install prisma
          echo "DATABASE_URL=${{ secrets.DB_URL }}" > .env
          npx prisma migrate deploy --schema=./prisma/schema.prisma

      - name: Install dependencies and generate .env file
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          frontend_directory="$(pwd)/frontend/react-app"
          npm ci --prefix "$frontend_directory"
          env_file_path="$frontend_directory/.env"
          > "$env_file_path"
          jq -r '.AppStack | to_entries | .[] | "VITE_\(.key | ascii_upcase | gsub("([a-z])([A-Z])"; "\\1_\\2"))=\(.value)"' cdk_outputs.json >> "$env_file_path"
          cat "$env_file_path"

      - name: Run Frontend Build and Upload to S3 bucket
        run: |
          frontend_directory="$(pwd)/frontend/react-app"
          CI=false && npm run build --prefix "$frontend_directory"
          bucket_name=$(cat cdk_outputs.json | jq -r .AppStack.FrontendBucketName)
          aws s3 cp "$frontend_directory/dist" "s3://$bucket_name" --recursive

      - name: Invalidate CloudFront Cache
        run: |
          distribution_id=$(cat cdk_outputs.json | jq -r .AppStack.FrontendDistributionId)
          aws cloudfront create-invalidation --distribution-id "$distribution_id" --paths "/*"

      #- name: Destroy stack
      #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #  run: cdk destroy --app="cdk.out" --force --all
